<template>
  <div class="form-container">
    <v-form ref="form" v-model="valid" lazy-validation>
      <!-- Repurchase Type Selection (only for add mode) -->
      <v-row v-if="!isEdit">
        <v-col cols="12">
          <v-card variant="outlined" class="mb-4">
            <v-card-title>ເລືອກປະເພດການຊື້ຄືນ</v-card-title>
            <v-card-text>
              <v-radio-group v-model="repurchaseType" inline>
                <v-radio label="ຊື້ຄືນສິນຄ້າທີ່ມີຢູ່ແລ້ວ" value="existingProduct"></v-radio>
                <v-radio label="ຊື້ຄືນທອງໃໝ່ / ຈາກລູກຄ້າໃໝ່" value="newGold"></v-radio>
              </v-radio-group>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <v-row>
        <!-- Customer Information -->
        <v-col cols="12" md="6">
          <v-card variant="outlined" class="h-100">
            <v-card-title>ຂໍ້ມູນລູກຄ້າ</v-card-title>
            <v-card-text>
              <div v-if="repurchaseType === 'existingProduct' || isEdit">
                <v-autocomplete
                  v-model="formData.custId"
                  :items="customers"
                  item-title="name"
                  item-value="id"
                  label="ເລືອກລູກຄ້າ"
                  :rules="[rules.required]"
                  variant="outlined"
                  :loading="loading.customers"
                  :disabled="isEdit"
                >
                  <template v-slot:item="{ props, item }">
                    <v-list-item v-bind="props" :title="item.raw.name" :subtitle="item.raw.phone"></v-list-item>
                  </template>
                </v-autocomplete>
              </div>
              
              <div v-else-if="repurchaseType === 'newGold'">
                <v-text-field
                  v-model="formData.newCustomer.name"
                  label="ຊື່ລູກຄ້າໃໝ່"
                  :rules="[rules.required]"
                  variant="outlined"
                ></v-text-field>
                <v-text-field
                  v-model="formData.newCustomer.phone"
                  label="ເບີໂທລູກຄ້າໃໝ່"
                  :rules="[rules.required]"
                  variant="outlined"
                ></v-text-field>
                <v-textarea
                  v-model="formData.newCustomer.address"
                  label="ທີ່ຢູ່ລູກຄ້າໃໝ່"
                  rows="2"
                  variant="outlined"
                ></v-textarea>
              </div>
            </v-card-text>
          </v-card>
        </v-col>

        <!-- Product Selection -->
        <v-col cols="12" md="6">
          <v-card variant="outlined" class="h-100">
            <v-card-title>ເລືອກສິນຄ້າ</v-card-title>
            <v-card-text>
              <div v-if="repurchaseType === 'existingProduct' || isEdit">
                <v-autocomplete
                  v-model="formData.productIds"
                  :items="availableProducts"
                  item-title="name"
                  item-value="id"
                  label="ເລືອກສິນຄ້າທີ່ຊື້ຄືນ"
                  :disabled="!formData.custId"
                  :loading="loading.products"
                  multiple
                  chips
                  deletable-chips
                  :rules="[rules.arrayNotEmpty]"
                  variant="outlined"
                  :no-data-text="noDataTextForProducts"
                >
                  <template v-slot:item="{ props, item }">
                    <v-list-item v-bind="props" :title="item.raw.name" :subtitle="`ນ້ຳໜັກ: ${item.raw.weight}g`"></v-list-item>
                  </template>
                </v-autocomplete>
              </div>
              
              <div v-else-if="repurchaseType === 'newGold'">
                <v-text-field
                  v-model="autoGeneratedProductId"
                  label="ລະຫັດສິນຄ້າໃໝ່"
                  readonly
                  variant="outlined"
                  hint="ລະຫັດຈະຖືກສ້າງອັດຕະໂນມັດ"
                  persistent-hint
                ></v-text-field>
                <v-text-field
                  v-model="formData.newProduct.name"
                  label="ຊື່ສິນຄ້າໃໝ່"
                  :rules="[rules.required]"
                  variant="outlined"
                ></v-text-field>
                <v-text-field
                  v-model="formData.newProduct.type"
                  label="ປະເພດສິນຄ້າໃໝ່"
                  :rules="[rules.required]"
                  variant="outlined"
                ></v-text-field>
                <v-text-field
                  v-model.number="formData.newProduct.weight"
                  label="ນ້ຳໜັກ (ກຣາມ)"
                  type="number"
                  :rules="[rules.required, rules.positive]"
                  variant="outlined"
                ></v-text-field>
              </div>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <!-- Price Information -->
      <v-row class="mt-4">
        <v-col cols="12">
          <v-card variant="outlined">
            <v-card-title>ຂໍ້ມູນລາຄາ</v-card-title>
            <v-card-text>
              <v-row>
                <v-col cols="12" md="6">
                  <v-text-field
                    v-model="formData.repurchaseDate"
                    label="ວັນທີຊື້ຄືນ"
                    type="date"
                    :rules="[rules.required]"
                    variant="outlined"
                  ></v-text-field>
                </v-col>
                <v-col cols="12" md="6">
                  <v-text-field
                    v-model.number="formData.repurchasePrice"
                    label="ລາຄາຊື້ຄືນ (ກີບ)"
                    type="number"
                    :rules="[rules.required, rules.positive]"
                    variant="outlined"
                  ></v-text-field>
                </v-col>
                <v-col cols="12" md="6">
                  <v-text-field
                    v-model.number="formData.damageCost"
                    label="ຄ່າເສຍຫາຍຮູບປະພັນ (ກີບ)"
                    type="number"
                    :rules="[rules.nonNegative]"
                    variant="outlined"
                  ></v-text-field>
                </v-col>
                <v-col cols="12" md="6">
                  <v-text-field
                    v-model.number="formData.lostWeightFee"
                    label="ຄ່ານ້ຳໜັກທອງຫຼຸດ (ກີບ)"
                    type="number"
                    :rules="[rules.nonNegative]"
                    variant="outlined"
                  ></v-text-field>
                </v-col>
                <v-col cols="12" md="6">
                  <v-text-field
                    :model-value="formatCurrency(netRepurchasePrice)"
                    label="ລາຄາຊື້ຄືນສຸດທິ (ກີບ)"
                    readonly
                    variant="outlined"
                    color="success"
                  ></v-text-field>
                </v-col>
                <v-col cols="12" md="6">
                  <v-textarea
                    v-model="formData.reReason"
                    label="ເຫດຜົນການຊື້ຄືນ"
                    rows="2"
                    variant="outlined"
                  ></v-textarea>
                </v-col>
              </v-row>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <!-- Selected Products Details -->
      <v-row v-if="selectedProducts.length > 0" class="mt-4">
        <v-col cols="12">
          <v-card variant="tonal" color="blue-grey-lighten-5">
            <v-card-title>ລາຍລະອຽດສິນຄ້າທີ່ເລືອກ</v-card-title>
            <v-card-text>
              <v-table density="compact">
                <thead>
                  <tr>
                    <th>ຊື່ສິນຄ້າ</th>
                    <th>ປະເພດ</th>
                    <th>ນ້ຳໜັກ</th>
                    <th>ຄ່າກຳເຫນັດ</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="product in selectedProducts" :key="product.id">
                    <td>{{ product.name }}</td>
                    <td>{{ product.type }}</td>
                    <td>{{ product.weight }}g</td>
                    <td>
                      <v-chip color="success" size="small" variant="flat">
                        ບໍ່ມີຄ່າກຳເໜັດ
                      </v-chip>
                    </td>
                  </tr>
                </tbody>
              </v-table>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <!-- Form Actions -->
      <v-card-actions class="px-0 mt-6">
        <v-spacer />
        <v-btn variant="outlined" color="error" @click="cancel" :disabled="loading.saving">
          <v-icon start>mdi-close</v-icon>
          ຍົກເລີກ
        </v-btn>
        <v-btn color="primary" @click="save" :loading="loading.saving" :disabled="!valid">
          <v-icon start>{{ isEdit ? 'mdi-content-save' : 'mdi-plus' }}</v-icon>
          {{ isEdit ? 'ອັບເດດ' : 'ບັນທຶກ' }}
        </v-btn>
      </v-card-actions>
    </v-form>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue';
import useApi from '~/composables/useApi';

const api = useApi();

// Props & Emits
const props = defineProps({
  repurchaseData: Object,
  isEdit: Boolean
});

const emit = defineEmits(['saved', 'cancelled']);

// State
const form = ref(null);
const valid = ref(true);
const repurchaseType = ref('existingProduct');

const loading = ref({
  customers: false,
  products: false,
  saving: false
});

// Form Data
const formData = ref({
  custId: null,
  productIds: [],
  repurchasePrice: null,
  damageCost: 0,
  lostWeightFee: 0,
  repurchaseDate: new Date().toISOString().substr(0, 10),
  reReason: '',
  newCustomer: {
    name: '',
    phone: '',
    address: ''
  },
  newProduct: {
    name: '',
    type: '',
    weight: null
  }
});

// Data
const customers = ref([]);
const availableProducts = ref([]);

// Auto-generated product ID
const autoGeneratedProductId = computed(() => {
  if (repurchaseType.value === 'newGold') {
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
    return `RP${timestamp}${random}`;
  }
  return '';
});

// Validation Rules
const rules = {
  required: value => !!value || 'ກະລຸນາປ້ອນຂໍ້ມູນ',
  positive: value => (value > 0) || 'ຕ້ອງເປັນຄ່າບວກ',
  nonNegative: value => (value >= 0) || 'ຕ້ອງເປັນຄ່າບວກ ຫຼື ສູນ',
  arrayNotEmpty: value => (value && value.length > 0) || 'ກະລຸນາເລືອກຢ່າງໜ້ອຍ 1 ລາຍການ'
};

// Computed
const selectedProducts = computed(() => {
  return availableProducts.value.filter(p => formData.value.productIds.includes(p.id));
});

const netRepurchasePrice = computed(() => {
  const initial = parseFloat(formData.value.repurchasePrice) || 0;
  const damage = parseFloat(formData.value.damageCost) || 0;
  const lost = parseFloat(formData.value.lostWeightFee) || 0;
  const net = initial - damage - lost;
  return net >= 0 ? net : 0;
});

const noDataTextForProducts = computed(() => {
  if (loading.value.products) return 'ກຳລັງໂຫລດ...';
  if (!formData.value.custId) return 'ກະລຸນາເລືອກລູກຄ້າກ່ອນ';
  return 'ບໍ່ພົບສິນຄ້າທີ່ລູກຄ້ານີ້ເຄີຍຊື້';
});

// Watchers
watch(() => formData.value.custId, (newCustId) => {
  if ((repurchaseType.value === 'existingProduct' || props.isEdit) && newCustId) {
    formData.value.productIds = [];
    fetchProductsForCustomer(newCustId);
  } else {
    availableProducts.value = [];
    formData.value.productIds = [];
  }
});

watch(repurchaseType, (newType) => {
  // Reset form when changing type
  formData.value.custId = null;
  formData.value.productIds = [];
  formData.value.newCustomer = { name: '', phone: '', address: '' };
  formData.value.newProduct = { name: '', type: '', weight: null };
  availableProducts.value = [];
  
  if (newType === 'existingProduct' && customers.value.length === 0) {
    fetchCustomers();
  }
});

// API Functions
const fetchCustomers = async () => {
  loading.value.customers = true;
  try {
    const response = await api.get('/customers');
    customers.value = (response || []).map(customer => ({
      id: customer.Cust_ID,
      name: customer.Cust_name,
      phone: customer.Phone,
      address: customer.Address
    }));
  } catch (error) {
    console.error('Error fetching customers:', error);
  } finally {
    loading.value.customers = false;
  }
};

const fetchProductsForCustomer = async (customerId) => {
  loading.value.products = true;
  availableProducts.value = [];
  try {
    const response = await api.get(`/customers/${customerId}/products`);
    availableProducts.value = response || [];
  } catch (error) {
    console.error('Error fetching products for customer:', error);
  } finally {
    loading.value.products = false;
  }
};

// Actions
const save = async () => {
  const { valid: formValid } = await form.value.validate();
  if (!formValid) {
    return;
  }

  loading.value.saving = true;
  try {
    let payload = {
      repurchasePrice: formData.value.repurchasePrice,
      damageCost: formData.value.damageCost,
      lostWeightFee: formData.value.lostWeightFee,
      repurchaseDate: formData.value.repurchaseDate,
      reReason: formData.value.reReason,
      type: repurchaseType.value
    };

    if (repurchaseType.value === 'existingProduct' || props.isEdit) {
      payload.custId = formData.value.custId;
      payload.productIds = formData.value.productIds;
    } else if (repurchaseType.value === 'newGold') {
      payload.newCustomer = formData.value.newCustomer;
      payload.newProduct = {
        Pd_ID: autoGeneratedProductId.value,
        Pd_Name: formData.value.newProduct.name,
        Type_Name: formData.value.newProduct.type,
        Weight: formData.value.newProduct.weight,
        Pattern_Value: 0
      };
    }

    if (props.isEdit) {
      await api.put(`/repurchases/${props.repurchaseData.Re_ID}`, payload);
    } else {
      await api.post('/repurchases', payload);
    }

    emit('saved');
  } catch (error) {
    console.error('Error saving repurchase:', error);
  } finally {
    loading.value.saving = false;
  }
};

const cancel = () => {
  emit('cancelled');
};

// Utility Functions
const formatCurrency = (value) => {
  if (value == null) return '0 ກີບ';
  return new Intl.NumberFormat('lo-LA').format(value) + ' ກີບ';
};

// Initialize
onMounted(() => {
  if (props.isEdit && props.repurchaseData) {
    // Load edit data
    const data = props.repurchaseData;
    formData.value.custId = data.Tb_Customer?.Cust_ID || null;
    formData.value.repurchasePrice = data.Repurchase_Price;
    formData.value.damageCost = data.Damage_Cost || 0;
    formData.value.lostWeightFee = data.Loose_Gold_Cost || 0;
    formData.value.repurchaseDate = new Date(data.Re_date).toISOString().substr(0, 10);
    formData.value.reReason = data.Re_reason || '';
    formData.value.productIds = data.Tb_Product?.map(p => p.Pd_ID) || [];
    
    // Fetch required data for edit
    fetchCustomers();
    if (formData.value.custId) {
      fetchProductsForCustomer(formData.value.custId);
    }
  } else {
    // Load customers for new form
    fetchCustomers();
  }
});
</script>

<style scoped>
.form-container {
  background: white;
  border-radius: 16px;
  padding: 24px;
  box-shadow: 0 4px 20px rgba(54, 90, 118, 0.08);
  border: 1px solid rgba(54, 90, 118, 0.1);
}

.v-card {
  border-radius: 12px !important;
}

.v-card-title {
  background: linear-gradient(135deg, rgba(54, 90, 118, 0.1) 0%, rgba(54, 90, 118, 0.05) 100%);
  color: #365a76 !important;
  font-weight: 600 !important;
}

.h-100 {
  height: 100%;
}
</style> 